# Bootloader installation (GRUB2) — values follow Debian's calamares-settings
---
efiBootLoader: "grub"

kernel: "/vmlinuz-linux"
img: "/initramfs-linux.img"
fallback: "/initramfs-linux-fallback.img"
timeout: "0"

grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "grub-probe"
efiBootMgr: "efibootmgr"

bootloaderEntryName: "TenebraOS"

installEFIFallback: true
