# fstab — mount options for the installed system
---
mountOptions:
    default: defaults,noatime
    btrfs: defaults,noatime
ssdExtraMountOptions:
    ext4: discard
    xfs: discard
    btrfs: discard
crypttabOptions: luks,discard