# users — installed-system user setup
---
defaultGroups:
    - sudo
    - adm
    - netdev
    - lpadmin
    - plugdev
    - users

sudoersGroup: sudo
autologinGroup: autologin
doAutologin: false

setRootPassword: false
doReusePassword: true

userShell: /bin/bash

hostname:
    location: EtcFile
    editable: true
