# TenebraOS Calamares settings
---
modules-search:
    - /usr/share/calamares/modules
    - /usr/lib/calamares/modules

sequence:
    - show:
        - welcome
        - usecase_select
        - locale
        - keyboard
        - partition
        - users
        - summary
    - exec:
        - partition
        - hardware_detect
        - users
        - networkcfg
        - grubcfg
        - bootloader
        - hwclock
        - services
        - packages
        - autoconfig
        - umount
        - finished
