#!/bin/bash
# bare/06-master-build.sh
# Phase 6: Master build orchestrator — finalizes the TenebraOS rootfs
#
# This script runs after all phases are complete and:
#   1. Copies the hybrid package manager into the rootfs
#   2. Installs default build profiles
#   3. Generates /etc/fstab from current partition UUIDs
#   4. Sets up the GRUB bootloader configuration
#   5. Creates the final rootfs tarball for deployment
#
# Usage:
#   sudo ./06-master-build.sh
#   sudo ./06-master-build.sh --target /dev/sdX   # generate fstab for target

set -euo pipefail

# ─── Configuration ─────────────────────────────────────────────────────────────
TENEBRA_BUILD="${TENEBRA_BUILD:-/tmp/tenebra-build}"
TENEBRA_ROOTFS="$TENEBRA_BUILD/rootfs"
TENEBRA_LOGS="$TENEBRA_BUILD/logs"
TENEBRA_TARGET_DEV="${TENEBRA_TARGET_DEV:-/dev/sdX}"

log()   { printf '\n\033[1;34m==>\033[0m \033[1m%s\033[0m\n' "$*"; }
err()   { printf '\n\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }
info()  { printf '\033[1;32m>>>\033[0m %s\n' "$*"; }

# ─── Install Package Manager ──────────────────────────────────────────────────
install_pkg_manager() {
    log "Installing tenebra-pkg into rootfs"

    local rootfs="$TENEBRA_ROOTFS"
    local pkgmanager="$(dirname "$0")/usr-local-bin/tenebra-pkg"

    if [ -f "$pkgmanager" ]; then
        mkdir -p "$rootfs/usr/local/bin"
        install -m 755 "$pkgmanager" "$rootfs/usr/local/bin/tenebra-pkg"
        ok "tenebra-pkg installed at /usr/local/bin/tenebra-pkg"
    else
        warn "tenebra-pkg source not found at $pkgmanager"
    fi
}

# ─── Install Build Profiles ────────────────────────────────────────────────────
install_profiles() {
    log "Installing default build profiles"

    local rootfs="$TENEBRA_ROOTFS"
    local profile_dir="$rootfs/etc/tenebra/profiles"
    mkdir -p "$profile_dir"

    # Default profiles
    for profile in desktop server gaming develop hardened; do
        cat > "$profile_dir/${profile}.conf" <<PROFILE
# TenebraOS build profile: $profile
# Generated by 06-master-build.sh

PROFILE
    done

    # Copy from the bare directory if available
    local src_profiles="$(dirname "$0")/profiles"
    if [ -d "$src_profiles" ]; then
        cp "$src_profiles"/*.conf "$profile_dir/" 2>/dev/null || true
    fi

    ok "Build profiles installed in $profile_dir"
}

# ─── Generate fstab ────────────────────────────────────────────────────────────
generate_fstab() {
    log "Generating /etc/fstab"

    local rootfs="$TENEBRA_ROOTFS"
    local target="${TENEBRA_TARGET_DEV}"

    if [ "$target" = "/dev/sdX" ]; then
        info "No target device — using placeholder fstab"
        return 0
    fi

    local ROOT_PART="${target}2"
    local ESP_PART="${target}1"
    if [[ "$target" == *"nvme"* ]]; then
        ROOT_PART="${target}p2"
        ESP_PART="${target}p1"
    fi

    local ROOT_UUID
    ROOT_UUID="$(blkid -s UUID -o value "$ROOT_PART" 2>/dev/null || echo "ROOT_UUID")"
    local ESP_UUID
    ESP_UUID="$(blkid -s UUID -o value "$ESP_PART" 2>/dev/null || echo "ESP_UUID")"

    cat > "$rootfs/etc/fstab" <<FSTAB
# TenebraOS fstab — Auto-generated by 06-master-build.sh
# <device>                          <mount>     <type>  <options>                             <dump> <pass>
UUID=${ROOT_UUID}                   /           btrfs   subvol=@,compress=zstd:1,ssd,noatime  0      1
UUID=${ROOT_UUID}                   /home       btrfs   subvol=@home,compress=zstd:1,ssd      0      2
UUID=${ROOT_UUID}                   /snapshots  btrfs   subvol=@snapshots,compress=zstd:1,ssd 0      2
UUID=${ESP_UUID}                    /boot       vfat    umask=0077                            0      2
proc                               /proc       proc    nosuid,noexec,nodev                   0      0
sysfs                              /sys        sysfs   nosuid,noexec,nodev,ro               0      0
tmpfs                              /tmp        tmpfs   nosuid,nodev,size=2G                  0      0
tmpfs                              /run        tmpfs   nosuid,nodev,size=2G                  0      0
FSTAB

    ok "fstab written with UUIDs: ROOT=$ROOT_UUID ESP=$ESP_UUID"
}

# ─── Finalize Rootfs ───────────────────────────────────────────────────────────
finalize_rootfs() {
    log "Finalizing rootfs"

    local rootfs="$TENEBRA_ROOTFS"

    # Set proper permissions
    chmod 1777 "$rootfs/tmp"
    chmod 1777 "$rootfs/run"

    # Create necessary device nodes if not present
    for node in console null zero random urandom tty; do
        case "$node" in
            console)  [ -c "$rootfs/dev/console" ]  || mknod "$rootfs/dev/console" c 5 1 2>/dev/null || true ;;
            null)     [ -c "$rootfs/dev/null" ]     || mknod "$rootfs/dev/null" c 1 3 2>/dev/null || true ;;
            zero)     [ -c "$rootfs/dev/zero" ]     || mknod "$rootfs/dev/zero" c 1 5 2>/dev/null || true ;;
            random)   [ -c "$rootfs/dev/random" ]   || mknod "$rootfs/dev/random" c 1 8 2>/dev/null || true ;;
            urandom)  [ -c "$rootfs/dev/urandom" ]  || mknod "$rootfs/dev/urandom" c 1 9 2>/dev/null || true ;;
            tty)      [ -c "$rootfs/dev/tty" ]      || mknod "$rootfs/dev/tty" c 5 0 2>/dev/null || true ;;
        esac
    done

    # Copy the keyring for the TenebraOS repo
    mkdir -p "$rootfs/usr/share/keyrings"
    local keyring="$(dirname "$0")/../config/includes.chroot/usr/share/keyrings/tenebraos-repo.gpg"
    if [ -f "$keyring" ]; then
        cp "$keyring" "$rootfs/usr/share/keyrings/"
    fi

    # Create /etc/resolv.conf if missing
    [ -f "$rootfs/etc/resolv.conf" ] || echo "nameserver 1.1.1.1" > "$rootfs/etc/resolv.conf"

    # Set the default shell for root
    chroot "$rootfs" chsh -s /bin/bash root 2>/dev/null || true

    info "Rootfs finalized"
}

# ─── Create Deployment Tarball ─────────────────────────────────────────────────
create_tarball() {
    log "Creating rootfs deployment tarball"

    local rootfs="$TENEBRA_ROOTFS"
    local output="$TENEBRA_BUILD/tenebraos-rootfs.tar.xz"

    # Unmount pseudo-fs if mounted
    for m in dev/pts dev proc sys run; do
        mountpoint -q "$rootfs/$m" 2>/dev/null && umount "$rootfs/$m" 2>/dev/null || true
    done

    # Create tarball
    tar cJf "$output" \
        --one-file-system \
        --exclude='./dev/*' \
        --exclude='./proc/*' \
        --exclude='./sys/*' \
        --exclude='./run/*' \
        --exclude='./tmp/*' \
        -C "$rootfs" . 2>/dev/null

    local size
    size="$(du -h "$output" | cut -f1)"
    ok "Rootfs tarball created: $output ($size)"
}

# ─── Print Summary ─────────────────────────────────────────────────────────────
print_summary() {
    log "TenebraOS Build Complete"
    echo ""
    echo "Rootfs location: $TENEBRA_ROOTFS"
    echo ""
    echo "Installed components:"
    echo "  - Cross-toolchain: binutils + gcc + glibc"
    echo "  - Core userland:   coreutils, bash, util-linux, btrfs-progs, dbus, elogind"
    echo "  - Linux kernel:    $(ls "$TENEBRA_ROOTFS/boot/vmlinuz-"* 2>/dev/null | head -1 | xargs basename 2>/dev/null || echo 'not built')"
    echo "  - Init system:     $(cat "$TENEBRA_BUILD/.init-system" 2>/dev/null || echo 'not set')"
    echo "  - Package manager: tenebra-pkg at /usr/local/bin/"
    echo "  - Snapshots:       Snapper + grub-btrfs integration"
    echo ""
    echo "To deploy:"
    echo "  1. Boot from the rootfs tarball or directly mount the target disk"
    echo "  2. Run: tenebra-pkg profile apply desktop"
    echo "  3. Run: tenebra-pkg upgrade"
    echo ""
    echo "To install from a live system:"
    echo "  sudo tar xJf /tmp/tenebra-build/tenebraos-rootfs.tar.xz -C /mnt"
    echo "  sudo grub-install /dev/sdX"
    echo "  sudo update-grub"
}

# ─── Main ──────────────────────────────────────────────────────────────────────
main() {
    [ "$(id -u)" -eq 0 ] || { echo "Must run as root" >&2; exit 1; }
    [ -d "$TENEBRA_ROOTFS" ] || err "Rootfs not found — run 01-bootstrap.sh first"

    # Parse arguments
    while [ $# -gt 0 ]; do
        case "$1" in
            --target) TENEBRA_TARGET_DEV="$2"; shift 2 ;;
            *) shift ;;
        esac
    done

    install_pkg_manager
    install_profiles
    generate_fstab
    finalize_rootfs
    create_tarball
    print_summary
}

main "$@"
